module.exports = [
    {
      city: "Tbilisi",
      lat: "41.7225",
      lng: "44.7925",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Tbilisi",
      capital: "primary",
      population: "1118035",
      population_proper: "1118035"
    },
    {
      city: "Batumi",
      lat: "41.6458",
      lng: "41.6417",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "admin",
      population: "154600",
      population_proper: "154600"
    },
    {
      city: "Kutaisi",
      lat: "42.2500",
      lng: "42.7000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "admin",
      population: "147900",
      population_proper: "147900"
    },
    {
      city: "Rustavi",
      lat: "41.5333",
      lng: "45.0000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "admin",
      population: "128680",
      population_proper: "128680"
    },
    {
      city: "Sokhumi",
      lat: "43.0033",
      lng: "41.0153",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "admin",
      population: "64441",
      population_proper: "64441"
    },
    {
      city: "Gori",
      lat: "41.9817",
      lng: "44.1124",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "admin",
      population: "48143",
      population_proper: "48143"
    },
    {
      city: "Zugdidi",
      lat: "42.5083",
      lng: "41.8667",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "admin",
      population: "42998",
      population_proper: "42998"
    },
    {
      city: "Poti",
      lat: "42.1500",
      lng: "41.6667",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "41465",
      population_proper: "41465"
    },
    {
      city: "Tskhinvali",
      lat: "42.2257",
      lng: "43.9701",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "",
      population: "30432",
      population_proper: "30432"
    },
    {
      city: "Khashuri",
      lat: "41.9975",
      lng: "43.5986",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "minor",
      population: "26135",
      population_proper: "26135"
    },
    {
      city: "Samtredia",
      lat: "42.1625",
      lng: "42.3417",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "25318",
      population_proper: "25318"
    },
    {
      city: "Senaki",
      lat: "42.2689",
      lng: "42.0678",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "21596",
      population_proper: "21596"
    },
    {
      city: "Marneuli",
      lat: "41.4969",
      lng: "44.8108",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "20211",
      population_proper: "20211"
    },
    {
      city: "Telavi",
      lat: "41.9167",
      lng: "45.4833",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "admin",
      population: "19629",
      population_proper: "19629"
    },
    {
      city: "Akhaltsikhe",
      lat: "41.6389",
      lng: "42.9861",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "admin",
      population: "17903",
      population_proper: "17903"
    },
    {
      city: "Gardabani",
      lat: "41.4500",
      lng: "45.1000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "15100",
      population_proper: "15100"
    },
    {
      city: "Ozurgeti",
      lat: "41.9269",
      lng: "42.0006",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "admin",
      population: "14785",
      population_proper: "14785"
    },
    {
      city: "Kaspi",
      lat: "41.9250",
      lng: "44.4222",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "minor",
      population: "13423",
      population_proper: "13423"
    },
    {
      city: "Chiatura",
      lat: "42.2903",
      lng: "43.2819",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "12803",
      population_proper: "12803"
    },
    {
      city: "Tsqaltubo",
      lat: "42.3264",
      lng: "42.6006",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "11281",
      population_proper: "11281"
    },
    {
      city: "Sagarejo",
      lat: "41.7333",
      lng: "45.3333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "10871",
      population_proper: "10871"
    },
    {
      city: "Borjomi",
      lat: "41.8389",
      lng: "43.3792",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "",
      population: "10546",
      population_proper: "10546"
    },
    {
      city: "T’q’ibuli",
      lat: "42.3503",
      lng: "42.9983",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "9770",
      population_proper: "9770"
    },
    {
      city: "Khoni",
      lat: "42.3167",
      lng: "42.4333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "8987",
      population_proper: "8987"
    },
    {
      city: "Bolnisi",
      lat: "41.4500",
      lng: "44.5333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "8967",
      population_proper: "8967"
    },
    {
      city: "Akhalkalaki",
      lat: "41.4056",
      lng: "43.4861",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "minor",
      population: "8295",
      population_proper: "8295"
    },
    {
      city: "Gurjaani",
      lat: "41.7444",
      lng: "45.8000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "8024",
      population_proper: "8024"
    },
    {
      city: "Mtskheta",
      lat: "41.8500",
      lng: "44.7167",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "admin",
      population: "7940",
      population_proper: "7940"
    },
    {
      city: "Q’vareli",
      lat: "41.9500",
      lng: "45.8167",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "7739",
      population_proper: "7739"
    },
    {
      city: "Gali",
      lat: "42.6333",
      lng: "41.7333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "7605",
      population_proper: "7605"
    },
    {
      city: "Akhmeta",
      lat: "42.0333",
      lng: "45.2000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "7105",
      population_proper: "7105"
    },
    {
      city: "Lanchkhuti",
      lat: "42.0875",
      lng: "42.0333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "minor",
      population: "6395",
      population_proper: "6395"
    },
    {
      city: "Dusheti",
      lat: "42.0845",
      lng: "44.6961",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "6167",
      population_proper: "6167"
    },
    {
      city: "Sachkhere",
      lat: "42.3389",
      lng: "43.4039",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "6140",
      population_proper: "6140"
    },
    {
      city: "Dedoplists’q’aro",
      lat: "41.4652",
      lng: "46.1045",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "5940",
      population_proper: "5940"
    },
    {
      city: "Lagodekhi",
      lat: "41.8222",
      lng: "46.2750",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "5918",
      population_proper: "5918"
    },
    {
      city: "Ochamchire",
      lat: "42.7100",
      lng: "41.4700",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "5280",
      population_proper: "5280"
    },
    {
      city: "Ninotsminda",
      lat: "41.2658",
      lng: "43.5889",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "",
      population: "5144",
      population_proper: "5144"
    },
    {
      city: "Algeti",
      lat: "41.4481",
      lng: "44.8953",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "5017",
      population_proper: "5017"
    },
    {
      city: "Abasha",
      lat: "42.2000",
      lng: "42.2167",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "4941",
      population_proper: "4941"
    },
    {
      city: "Tsnori",
      lat: "41.6125",
      lng: "45.9736",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "4815",
      population_proper: "4815"
    },
    {
      city: "Terjola",
      lat: "42.1833",
      lng: "42.9772",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "4644",
      population_proper: "4644"
    },
    {
      city: "Martvili",
      lat: "42.4167",
      lng: "42.3667",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "4425",
      population_proper: "4425"
    },
    {
      city: "Khobi",
      lat: "42.3167",
      lng: "41.9000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "4242",
      population_proper: "4242"
    },
    {
      city: "Bich’vinta",
      lat: "43.1667",
      lng: "40.3333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "4198",
      population_proper: "4198"
    },
    {
      city: "Tsalenjikha",
      lat: "42.6117",
      lng: "42.0706",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "3847",
      population_proper: "3847"
    },
    {
      city: "Vani",
      lat: "42.0839",
      lng: "42.5119",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "3744",
      population_proper: "3744"
    },
    {
      city: "Baghdati",
      lat: "42.0678",
      lng: "42.8247",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "3707",
      population_proper: "3707"
    },
    {
      city: "Chumlaq’i",
      lat: "41.7667",
      lng: "45.7736",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "3651",
      population_proper: "3651"
    },
    {
      city: "Dimi",
      lat: "42.0997",
      lng: "42.8219",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "3251",
      population_proper: "3251"
    },
    {
      city: "Tetri Ts’q’aro",
      lat: "41.5500",
      lng: "44.4667",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "3093",
      population_proper: "3093"
    },
    {
      city: "Vejini",
      lat: "41.7097",
      lng: "45.8303",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "2935",
      population_proper: "2935"
    },
    {
      city: "Babushara",
      lat: "42.8669",
      lng: "41.1328",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "2696",
      population_proper: "2696"
    },
    {
      city: "Tsinandali",
      lat: "41.8947",
      lng: "45.5756",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "2675",
      population_proper: "2675"
    },
    {
      city: "Dmanisi",
      lat: "41.3317",
      lng: "44.2037",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "2661",
      population_proper: "2661"
    },
    {
      city: "Tsalka",
      lat: "41.5983",
      lng: "44.0953",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "2326",
      population_proper: "2326"
    },
    {
      city: "Ambrolauri",
      lat: "42.5194",
      lng: "43.1500",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Rach’a-Lechkhumi da Kvemo Svaneti",
      capital: "admin",
      population: "2047",
      population_proper: "2047"
    },
    {
      city: "Chokhatauri",
      lat: "42.0189",
      lng: "42.2394",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "minor",
      population: "1815",
      population_proper: "1815"
    },
    {
      city: "Tsageri",
      lat: "42.6472",
      lng: "42.7700",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Rach’a-Lechkhumi da Kvemo Svaneti",
      capital: "minor",
      population: "1320",
      population_proper: "1320"
    },
    {
      city: "Rustavi",
      lat: "42.2897",
      lng: "43.8543",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "admin",
      population: "",
      population_proper: ""
    },
    {
      city: "Khelvachauri",
      lat: "41.5855",
      lng: "41.6719",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Zest’aponi",
      lat: "42.1092",
      lng: "43.0360",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Kobuleti",
      lat: "41.8214",
      lng: "41.7792",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Khulo",
      lat: "41.6459",
      lng: "42.3146",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Kareli",
      lat: "42.0244",
      lng: "43.9011",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Keda",
      lat: "41.6009",
      lng: "41.9401",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Chkhorots’q’u",
      lat: "42.5258",
      lng: "42.1321",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Shuakhevi",
      lat: "41.6242",
      lng: "42.1857",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Kharagauli",
      lat: "42.0129",
      lng: "43.2025",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Adigeni",
      lat: "41.6754",
      lng: "42.7031",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Asp’indza",
      lat: "41.5739",
      lng: "43.2483",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Tianeti",
      lat: "42.1083",
      lng: "44.9639",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Lent’ekhi",
      lat: "42.7889",
      lng: "42.7223",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Rach’a-Lechkhumi da Kvemo Svaneti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "St’epants’minda",
      lat: "42.6567",
      lng: "44.6433",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Mest’ia",
      lat: "43.0458",
      lng: "42.7278",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Oni",
      lat: "42.5794",
      lng: "43.4425",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Rach’a-Lechkhumi da Kvemo Svaneti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Akhalgori",
      lat: "42.1260",
      lng: "44.4833",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Java",
      lat: "42.3997",
      lng: "43.9367",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "",
      population_proper: ""
    }
  ]